import { NextRequest, NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { withAuth } from '@/middleware/withAuth';

export const GET = withAuth(async (req, { params, user }) => {
  try {
    const { meetingId } = params;
    const userId = user.userId;

    // Find the meeting by ID or Code
    const meeting = await prisma.meeting.findFirst({
      where: {
        OR: [
          { id: meetingId },
          { code: meetingId }
        ]
      },
      include: {
        participants: true
      }
    });

    if (!meeting) {
      return NextResponse.json({ error: 'Meeting not found' }, { status: 404 });
    }

    // Server-side guard: Only participants of this meeting can view the summary
    const isParticipant = meeting.participants.some(p => p.userId === userId);
    if (!isParticipant && meeting.hostId !== userId) {
      return NextResponse.json({ error: 'You are not authorized to view this summary' }, { status: 403 });
    }

    // Look up the meeting summary
    const summary = await prisma.meetingSummary.findUnique({
      where: { meetingId: meeting.id },
      include: {
        actionItems: true
      }
    });

    if (!summary) {
      // Find the latest recording for this meeting to assess state
      const latestRecording = await prisma.recording.findFirst({
        where: { meetingId: meeting.id },
        orderBy: { createdAt: 'desc' }
      });

      if (latestRecording) {
        if (latestRecording.status === 'PROCESSING') {
          return NextResponse.json({
            status: 'PROCESSING',
            message: 'Meeting summary is being generated by AI...'
          });
        }
        if (latestRecording.status === 'FAILED') {
          return NextResponse.json({
            status: 'FAILED',
            error: 'AI summary compilation failed. The recording might be corrupt or an AI service timeout occurred.'
          });
        }
      }

      return NextResponse.json({ error: 'No summary or recording found for this meeting' }, { status: 404 });
    }

    return NextResponse.json({
      status: 'READY',
      summary: {
        id: summary.id,
        meetingId: summary.meetingId,
        overview: summary.overview,
        keyDecisions: summary.keyDecisions,
        transcript: summary.transcript,
        model: summary.model,
        createdAt: summary.createdAt
      },
      actionItems: summary.actionItems
    });

  } catch (err: any) {
    console.error('Error fetching meeting summary:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
});
